//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.ClassStudents = new HashSet<ClassStudent>();
            this.ClassWeekDays = new HashSet<ClassWeekDay>();
            this.TrainingResults = new HashSet<TrainingResult>();
        }
    
        public long ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public long TeacherID { get; set; }
        public long CourseID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<ClassStudent> ClassStudents { get; set; }
        public virtual ICollection<ClassWeekDay> ClassWeekDays { get; set; }
        public virtual ICollection<TrainingResult> TrainingResults { get; set; }
    }
}
