//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public long CourseID { get; set; }
        public Nullable<int> Lessons { get; set; }
        public string Description { get; set; }
        public string Tern { get; set; }
        public long LanguageID { get; set; }
        public long LevelID { get; set; }
        public long CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Language Language { get; set; }
        public virtual Level Level { get; set; }
    }
}
