//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public long LevelID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
