//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long PaymentMethodID { get; set; }
        public Nullable<byte> Status { get; set; }
        public long StudentID { get; set; }
        public long ClassID { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Student Student { get; set; }
    }
}
