//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationClass
    {
        public long RegistrationClassID { get; set; }
        public long StudentID { get; set; }
        public long ClassID { get; set; }
    }
}
