//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.ClassStudents = new HashSet<ClassStudent>();
            this.Payments = new HashSet<Payment>();
            this.StudentAccounts = new HashSet<StudentAccount>();
            this.TrainingResultDetails = new HashSet<TrainingResultDetail>();
        }
    
        public long StudentID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<long> CityID { get; set; }
        public string FirtName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<ClassStudent> ClassStudents { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<StudentAccount> StudentAccounts { get; set; }
        public virtual ICollection<TrainingResultDetail> TrainingResultDetails { get; set; }
    }
}
