//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Classes = new HashSet<Class>();
            this.TeacherAccounts = new HashSet<TeacherAccount>();
        }
    
        public long TeacherID { get; set; }
        public string AvatarUrl { get; set; }
        public string FirtName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string NumberPhone { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<TeacherAccount> TeacherAccounts { get; set; }
    }
}
