//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingResultDetail
    {
        public long TrainingResultDetailID { get; set; }
        public long TrainingResultID { get; set; }
        public long StudentID { get; set; }
        public decimal ScoreFirt { get; set; }
        public Nullable<decimal> ScoreLast { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TrainingResult TrainingResult { get; set; }
    }
}
