//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageCenter.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekDay
    {
        public WeekDay()
        {
            this.ClassWeekDays = new HashSet<ClassWeekDay>();
        }
    
        public long WeekDayID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClassWeekDay> ClassWeekDays { get; set; }
    }
}
